Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-6.5"
  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
  #
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install java-1.7.0-openjdk-devel -y
    sudo yum install curl -y
    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -
    curl -L get.rvm.io | bash -s stable
    rvm requirements
    source ~/.rvm/rvm.sh
    sudo yum localinstall /vagrant_data/*.rpm -y
    sudo gem install bundler || true
  SHELL

  config.vm.define "gocd" do |gocd|
    gocd.vm.host_name = "gocd"
    gocd.vm.network "private_network", ip: "192.168.1.100"
  end

  config.vm.define "app" do |app|
    app.vm.host_name = "app"
    app.vm.network "private_network", ip: "192.168.1.101"
  end
end
